# Generated by Django 4.0.3 on 2022-04-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='like'),
        ),
    ]
